### ISSUE TITLE
Trouble using a hosted graphene Neo4j db

### ISSUE THREAD

**Issue by jalakoo** [elementsinteractive/flask-graphql-neo4j#9]
Hi, not a code issue so much as possible misunderstanding on my part.

I've tried unsuccessfully to modify the `docker-compose.yml` file to connect with a db hosted by graphened. Every `docker-compose up` run the app wants to spin up it's own local Neo4j instance instead of connecting to it.

Is using a remote neo4j instance doable with this POC?

Have also tried just removing the `neo4j` service like so, but there terminal just perpetually waits:
```
version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - flask-graphql-neo4j-dev
    environment:
      - NEO4J_HOST=_bolt_address_
      - NEO4J_PORT=_matching_port_
      - NEO4J_USER=_username_
      - NEO4J_PASSWORD=_password_
      - BIND_HOST=0.0.0.0
      - BIND_PORT=8080
    ports:
      - 127.0.0.1:8080:8080
networks:
  flask-graphql-neo4j-dev: {}
```
